name: 'metaGPT: update flake'
on:
  workflow_dispatch: null
  schedule:
  - cron: 0 */12 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  update_flake:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬆ Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: ✓ Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel recursive-nix
          download-buffer-size = 10485760
          accept-flake-config = true
    - name: 'Flake: update'
      run: 'nix flake update --accept-flake-config'
    - name: 'Deps: refresh'
      run: 'nix develop --accept-flake-config --command uvlock'
    - name: 'Create PR'
      uses: peter-evans/create-pull-request@v7
      with:
        title: "Auto-update artifacts"
        body: |
          This PR was created automatically by GitHub Actions.
        branch: "auto-update-artifacts"
        token: ${{ secrets.PAT  }}
        sign-commits: true
        delete-branch: true
        base: master
